Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,3 +1,68 @@
+# name: Threadfix connector
+
+# on: [ push ]
+
+# permissions:
+#   security-events: read
+#   contents: read
+  
+# jobs:
+#   create_input_file:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: GET code scanning alerts
+#         uses: actions/checkout@v3
+#       # this should be a script and should pull content based on pagination
+#       # should also guard against no content 
+#       - run: | 
+#               curl --request GET \
+#               --url https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?per_page=100 \
+#               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+#               --header 'content-type: application/json'\
+#               > ./input_file.json
+              
+#       - name: Validate file 
+#         run : |
+#               cat input_file.json | grep "number" >/dev/null && echo "got data!" || exit 1; 
+          
+#       - name: Debug failure
+#         if: failure()
+#         run: |
+#              cat input_file.json && echo "no valid data to work with!"
+         
+#       - name: Upload SARIF file
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: SARIF
+#           path: input_file.json
+       
+          
+#   create_output_file:
+#     runs-on: ubuntu-latest
+#     needs: create_input_file
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#       - name: Set up Python
+#         uses: actions/setup-python@v4
+#         with:
+#          python-version: '3.10'
+#       - name: Download json file and echo it
+#         uses: actions/download-artifact@v3
+#         with:
+#          name: SARIF
+#       - shell: bash
+#         run: |
+#           value=`cat input_file.json`
+#           echo $value
+#       - name: Run conversion script
+#         run: python sarif_converter.py input_file.json test.threadfix
+#       - name: look around
+#         run: |
+#           value=`cat test.threadfix`
+#           echo $value
+#           ls -a
+
 name: Threadfix connector
 
 on: [ push ]
@@ -14,12 +79,10 @@ jobs:
         uses: actions/checkout@v3
       # this should be a script and should pull content based on pagination
       # should also guard against no content 
-      - run: | 
-              curl --request GET \
-              --url https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?per_page=100 \
-              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-              --header 'content-type: application/json'\
-              > ./input_file.json
+      - run: gh api repos/dsp-testing/alex-testing/code-scanning/alerts > ./input.json
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  
               
       - name: Validate file 
         run : |
@@ -35,34 +98,4 @@ jobs:
         with:
           name: SARIF
           path: input_file.json
-       
-          
-  create_output_file:
-    runs-on: ubuntu-latest
-    needs: create_input_file
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-         python-version: '3.10'
-      - name: Download json file and echo it
-        uses: actions/download-artifact@v3
-        with:
-         name: SARIF
-      - shell: bash
-        run: |
-          value=`cat input_file.json`
-          echo $value
-      - name: Run conversion script
-        run: python sarif_converter.py input_file.json test.threadfix
-      - name: look around
-        run: |
-          value=`cat test.threadfix`
-          echo $value
-          ls -a
- 
- 
-        
-
+      
